name: cv_corrector
description: Professional CV Analyzer, Corrector & Career Toolkit
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP & API
  http: ^1.2.2

  # File Picking & PDF Reading
  file_picker: ^8.1.2
  syncfusion_flutter_pdf: ^27.1.48

  # UI & Animations
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3

  # Storage
  shared_preferences: ^2.3.3

  # Utils
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
