import 'dart:io';
import 'dart:ui' show Offset, Rect;
import 'package:file_picker/file_picker.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';

class PdfGenerator {
  static Future<File> generateCoverLetterPdf({
    required String coverLetterText,
    required String candidateName,
  }) async {
    final document = PdfDocument();
    final page = document.pages.add();
    final graphics = page.graphics;
    final pageSize = page.getClientSize();

    final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 11, style: PdfFontStyle.bold);
    final bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 10.5);
    final smallFont = PdfStandardFont(PdfFontFamily.helvetica, 9);

    double y = 0;
    final paragraphs = coverLetterText.split('\n');

    for (final line in paragraphs) {
      final trimmed = line.trim();
      if (trimmed.isEmpty) {
        y += 14;
        continue;
      }

      final isHeader = trimmed.startsWith('Re:') || trimmed.startsWith('Dear ');
      final isSignature = trimmed.startsWith('Yours ') ||
          trimmed.startsWith('Mr.') || trimmed.startsWith('Ms.') ||
          trimmed.startsWith('Mrs.') || trimmed.startsWith('Cell:');

      final font = (isHeader || isSignature) ? titleFont : bodyFont;

      final textElement = PdfTextElement(
        text: trimmed,
        font: font,
        brush: PdfBrushes.black,
        format: PdfStringFormat(lineSpacing: 4),
      );

      final layoutResult = textElement.draw(
        page: page,
        bounds: Rect.fromLTWH(40, y, pageSize.width - 80, pageSize.height - y - 40),
      );

      if (layoutResult != null) {
        y = layoutResult.bounds.bottom + 4;
      } else {
        y += 16;
      }

      if (y > pageSize.height - 60) {
        document.pages.add();
        y = 20;
      }
    }

    graphics.drawString(
      'Generated by CV Analyzer Pro',
      smallFont,
      brush: PdfBrushes.gray,
      bounds: Rect.fromLTWH(40, pageSize.height - 30, pageSize.width - 80, 20),
    );

    final dir = await getTemporaryDirectory();
    final safeName = candidateName.replaceAll(RegExp(r'[^\w\s]'), '').replaceAll(' ', '_');
    final path = '${dir.path}/${safeName}_Cover_Letter.pdf';
    final file = File(path);
    await file.writeAsBytes(await document.save());
    document.dispose();

    return file;
  }

  static Future<File> generateCorrectedCvPdf({
    required String correctedCvText,
    required String candidateName,
  }) async {
    final document = PdfDocument();

    final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 13, style: PdfFontStyle.bold);
    final sectionFont = PdfStandardFont(PdfFontFamily.helvetica, 11, style: PdfFontStyle.bold);
    final bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 10);
    final smallFont = PdfStandardFont(PdfFontFamily.helvetica, 9);

    PdfPage page = document.pages.add();
    final pageSize = page.getClientSize();
    double y = 0;

    final lines = correctedCvText.split('\n');

    final sectionKeywords = [
      'PROFILE', 'SUMMARY', 'OBJECTIVE', 'EXPERIENCE', 'WORK EXPERIENCE',
      'EDUCATION', 'SKILLS', 'TECHNICAL SKILLS', 'PROJECTS', 'CERTIFICATIONS',
      'AWARDS', 'REFERENCES', 'LANGUAGES', 'INTERESTS', 'CONTACT',
      'PROFESSIONAL SUMMARY', 'PERSONAL DETAILS', 'QUALIFICATIONS',
    ];

    bool isFirstLine = true;

    for (final line in lines) {
      final trimmed = line.trim();

      if (trimmed.isEmpty) {
        y += 10;
        continue;
      }

      PdfFont font;
      bool drawLine = false;

      if (isFirstLine) {
        font = titleFont;
        isFirstLine = false;
      } else if (sectionKeywords.any((kw) => trimmed.toUpperCase().startsWith(kw))) {
        font = sectionFont;
        drawLine = true;
        y += 8;
      } else {
        font = bodyFont;
      }

      if (y > pageSize.height - 80) {
        page = document.pages.add();
        y = 20;
      }

      if (drawLine) {
        page.graphics.drawLine(
          PdfPen(PdfColor(56, 189, 248), width: 1.5),
          Offset(40, y - 2),
          Offset(pageSize.width - 40, y - 2),
        );
        y += 4;
      }

      final textElement = PdfTextElement(
        text: trimmed,
        font: font,
        brush: PdfBrushes.black,
        format: PdfStringFormat(lineSpacing: 3),
      );

      final layoutResult = textElement.draw(
        page: page,
        bounds: Rect.fromLTWH(40, y, pageSize.width - 80, pageSize.height - y - 40),
      );

      if (layoutResult != null) {
        y = layoutResult.bounds.bottom + 3;
      } else {
        y += 14;
      }
    }

    page.graphics.drawString(
      'Generated by CV Analyzer Pro',
      smallFont,
      brush: PdfBrushes.gray,
      bounds: Rect.fromLTWH(40, pageSize.height - 30, pageSize.width - 80, 20),
    );

    final dir = await getTemporaryDirectory();
    final safeName = candidateName.replaceAll(RegExp(r'[^\w\s]'), '').replaceAll(' ', '_');
    final path = '${dir.path}/${safeName}_Corrected_CV.pdf';
    final file = File(path);
    await file.writeAsBytes(await document.save());
    document.dispose();

    return file;
  }

  /// Saves a generated PDF using a native file-save dialog.
  /// Returns the saved path, or null if user cancelled.
  static Future<String?> savePdfWithDialog(File tempFile, String defaultFileName) async {
    final result = await FilePicker.platform.saveFile(
      dialogTitle: 'Save PDF',
      fileName: defaultFileName,
      type: FileType.custom,
      allowedExtensions: ['pdf'],
    );

    if (result == null) return null;

    final savePath = result.endsWith('.pdf') ? result : '$result.pdf';
    await tempFile.copy(savePath);
    return savePath;
  }

  /// Opens the folder containing the saved file (Windows).
  static Future<void> openFileLocation(String filePath) async {
    await Process.run('explorer', ['/select,', filePath]);
  }
}
